server {
    listen 80;
    server_name nexcure.site;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name nexcure.site;

    ssl_certificate /etc/letsencrypt/live/yourdomain.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/yourdomain.com/privkey.pem;

    location / {
        proxy_pass http://web:8000;
    }
}